// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6eb10c39-8a32-4a6c-a7b7-b54f70a6789b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_aISexcZIc",
    "aws_user_pools_web_client_id": "1dejutkdolm96apg3e4ushsg0o",
    "oauth": {}
};


export default awsmobile;
